# Question 1

Create an element -wise comparison(greater,greater_equal, less and less_equal) of two arrays

In [18]:
import numpy as np
array1 = np.array([25,30])
array2 = np.array([35,40])
 # print original arrays.
print(array1)
print(array2)
#print("Greater than  between array1 and aaray2")
print(np.greater(array1,array2))
#print greater than or equal to between array1 and array2
print(np.greater_equal(array1,array2))
#print less than between array1 and array 2
print(np.less(array1,array2))
#print less than or equal to between array1 and array2
print(np.less_equal (array1,array2))

[25 30]
[35 40]
[False False]
[False False]
[ True  True]
[ True  True]


# Question 2

Write a Numpy program to create an array of 10 zeros, 10 ones, 10 fives

In [1]:
import numpy as np

array = np.zeros(10)
print(array)
array = np.ones(10)
print(array)
array = np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Question 3

Write Numpy program to compute sum of all elements , sum of each column and sum of each row of a given array.

In [3]:
import numpy as np

y = np.array([[1,2,4],[3,5,6]])
print(y)
print(np.sum(y))# sum of all elements
print(np.sum(y, axis =0)) # sum of each element
print (np.sum(y, axis = 1)) # sum of each row

[[1 2 4]
 [3 5 6]]
21
[ 4  7 10]
[ 7 14]


# Question 4

Write a Numpy program to add , subtract, multipy divide arguments element-wise

In [16]:
se = 6.0,2.0
import numpy as np

print(np.add(2.0, 6.0)) #adding the elements

print(np.subtract(2.0, 6.0))# subtracting the element
print(np.multiply(2.0, 6.0))# multiplying the elements
print(np.divide(2.0, 6.0))# divide the elemnts


8.0
-4.0
12.0
0.3333333333333333


# Question 5

Write a NumPy program to compute the trigonometric sine , cosine and tangent array of angles given in degree

In [17]:
import numpy as np
#print sine ;array of angles of given degrees
print(np.sin(np.array((0., 35., 40., 65.,90.))*np.pi / 180.))
# print cosine;array
print(np.cos(np.array((0., 35., 40., 65., 90.))*np.pi / 180.))
#print tangent; array of given angles in given degrees.
print(np.tan(np.array((0., 35., 40., 65., 90.))*np.pi /180.))

[0.         0.57357644 0.64278761 0.90630779 1.        ]
[1.00000000e+00 8.19152044e-01 7.66044443e-01 4.22618262e-01
 6.12323400e-17]
[0.00000000e+00 7.00207538e-01 8.39099631e-01 2.14450692e+00
 1.63312394e+16]
